import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { Metadata } from "next";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata:Metadata = {
  title: {
    default: "Flavor",
    template: "%s | Flavor",
  },
  description: "Generated by create next app" as string,
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body style={{ fontFamily: "sans-serif" }} className=" flex flex-col">
        <Header />
        <div className=" min-h-screen mx-auto max-w-6xl w-full px-2 mt-20 md:px-0">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
